#!/bin/sh

usage()
{
  echo "usage: $0 REGEX [MATCHING_GROUP_ID]"
	echo "example: echo test123abc | $0 \"test(.*)abc\""
}

if [ "$#" -eq 0 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then
  usage
  exit 0
fi

if [ -n "$2" ]
then
  g=$2
else
  g=1
fi
sed -nr "s/.*$1.*/\\$g/p"
